### ISSUE TITLE
Integrate to NosQLUnit

### ISSUE THREAD

**Issue by lordofthejars** [joschi/nosqlunit-elasticsearch2#1]
Hello, NoSQLUnit has been released yesterday with 0.9.0 but soon will come with other versions more regularly. Would you like to contribute with the support of ES 2 support? Of course this would mean stop supporting ES 1, but well I don't know who are really using ES 1 nowadays :)

**Comment by joschi** [comment]
@lordofthejars I will submit a PR to the NoSQL Unit project.

> Of course this would mean stop supporting ES 1, but well I don't know who are really using ES 1 nowadays

As a matter of fact I am one of those people. :wink:
I think we could simply add it as an additional module to NoSQL Unit (keeping the "nosqlunit-elasticsearch2" name).

**Comment by lordofthejars** [comment]
Great, if you think it is easy, then let's do it as you mention :)

El dl., 4 abr. 2016 a les 14:47, Jochen Schalanda (notifications@github.com)
va escriure:

**Comment by joschi** [comment]
Merged in lordofthejars/nosql-unit#155
